GET http://localhost:5000/api/links/2
Content-Type: application/json

###

POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "username": "user6",
  "password": "12345678"
}

###

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "username": "user6",
  "password": "1234678"
}

###

POST http://localhost:5000/api/links/2
Content-Type: application/json

{
  "title": "Hulu",
  "url": "https://www.hulu.com"
}
